/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_B */
#define LED_B_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_0_INBUF_ENABLED 0u
#define LED_B_0_INIT_DRIVESTATE 0u
#define LED_B_0_INIT_MUXSEL 0u
#define LED_B_0_INPUT_SYNC 2u
#define LED_B_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_0_NUM 4u
#define LED_B_0_PORT GPIO_PRT12
#define LED_B_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_B_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_INBUF_ENABLED 0u
#define LED_B_INIT_DRIVESTATE 0u
#define LED_B_INIT_MUXSEL 0u
#define LED_B_INPUT_SYNC 2u
#define LED_B_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_NUM 4u
#define LED_B_PORT GPIO_PRT12
#define LED_B_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_R */
#define LED_R_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_0_INBUF_ENABLED 0u
#define LED_R_0_INIT_DRIVESTATE 0u
#define LED_R_0_INIT_MUXSEL 0u
#define LED_R_0_INPUT_SYNC 2u
#define LED_R_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_0_NUM 5u
#define LED_R_0_PORT GPIO_PRT12
#define LED_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_R_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_INBUF_ENABLED 0u
#define LED_R_INIT_DRIVESTATE 0u
#define LED_R_INIT_MUXSEL 0u
#define LED_R_INPUT_SYNC 2u
#define LED_R_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_NUM 5u
#define LED_R_PORT GPIO_PRT12
#define LED_R_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* BUTTON */
#define BUTTON_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define BUTTON_0_INBUF_ENABLED 1u
#define BUTTON_0_INIT_DRIVESTATE 0u
#define BUTTON_0_INIT_MUXSEL 0u
#define BUTTON_0_INPUT_SYNC 2u
#define BUTTON_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BUTTON_0_NUM 4u
#define BUTTON_0_PORT GPIO_PRT0
#define BUTTON_0_SLEWRATE CY_GPIO_SLEW_FAST
#define BUTTON_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define BUTTON_DRIVEMODE CY_GPIO_DM_HIGHZ
#define BUTTON_INBUF_ENABLED 1u
#define BUTTON_INIT_DRIVESTATE 0u
#define BUTTON_INIT_MUXSEL 0u
#define BUTTON_INPUT_SYNC 2u
#define BUTTON_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BUTTON_NUM 4u
#define BUTTON_PORT GPIO_PRT0
#define BUTTON_SLEWRATE CY_GPIO_SLEW_FAST
#define BUTTON_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT9
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT9
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT9
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT9
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
